function list = families()
% lum.pattern.families lists the stimulus families the generator knows.
%
% One list, read by the generator to validate a family name and by the stimulus
% designer to fill its dropdown and explain each choice, so the two cannot drift.
%
% Returns a struct array:
%   .Name         Value of S.Stimulus.Generator.Family
%   .Label        What the designer shows
%   .Description  One sentence on what the family produces and what its groups vary
%   .Sweep        What more than two groups sweep, or '' when the family has no sweep
%
% This is a pure function: no hardware, no globals, unit-testable offline.
%
% See also: lum.pattern.generate, lum.gui.StimulusDesigner

list = struct( ...
    'Name', {'pure', 'sequence', 'occupancy', 'overlap_order', 'tiled_order', 'arbitrary'}, ...
    'Label', {'Pure channel', 'Sequence motif', 'Occupancy', 'Overlap order', ...
              'Tiled order (control)', 'Hand-drawn pulses'}, ...
    'Description', { ...
        ['One channel lit from stimulus onset for a fraction of the window. Two groups '...
         'give A against B.'], ...
        ['A motif of joint states repeated for a number of cycles, with a duty cycle per '...
         'channel. Two groups give the motif and its A/B mirror.'], ...
        ['The window shared between dark, A only, B only and both, as blocks or '...
         'shuffled. Two groups swap which channel''s block comes first.'], ...
        ['Pure blocks joined by a short and a long overlap guard, never dark. The groups '...
         'differ only in which channel leads across the short guard.'], ...
        ['A and B alternating bin by bin, B the exact complement of A: a control for '...
         'decoders that can read one channel alone.'], ...
        'Pulses typed in by hand, one row per pulse: group, channel, start and end.'}, ...
    'Sweep', {'lit fraction', 'phase of B against A', 'beta, the B share of the light', ...
              'phase of the cycle', '', ''});
