function list = families()
% lum.pattern.families lists the stimulus families the generator knows.
%
% A family is the kind of question a stimulus set asks the animal: which channel, how
% much of the mixture is A, which flashes more often, which comes first, which word.
% One list, read by the generator to validate a family name, and by the stimulus designer
% and the setup dialog to fill their dropdowns and explain each choice, so they cannot
% drift apart. docs/stimulus_family.md describes every family in full.
%
% Returns a struct array, in the order the windows offer them:
%   .Name         Value of S.Stimulus.Generator.Family
%   .Label        What the windows show
%   .Question     What the animal has to tell apart, as a question; '' for hand-drawn
%   .Description  A few sentences on what the family delivers and why
%   .PerTrial     What "a new pattern every trial" (Generator.Continuous) means for the
%                 family, as the checkbox says it; '' when the family does not offer it
%
% This is a pure function: no hardware, no globals, unit-testable offline.
%
% See also: lum.pattern.generate, lum.pattern.familyDefaults, lum.gui.StimulusDesigner

list = struct( ...
    'Name', {'pure', 'mixture', 'count', 'order', 'motif', 'arbitrary'}, ...
    'Label', {'Pure channel: A or B', 'Mixture: more A or more B', ...
              'Sequence: more A or more B flashes', 'Order: A first or B first', ...
              'Motifs: words of A and B', 'Hand-drawn pulses'}, ...
    'Question', {'Which channel is lit?', 'How much of the mixture is A?', ...
                 'Which channel flashes more often?', 'Which channel comes first?', ...
                 'Which word is it?', ''}, ...
    'Description', { ...
        ['Each trial lights one channel, A or B, from stimulus onset: A pays left, B pays '...
         'right. With several lit fractions the duration varies too, and only which channel '...
         'is lit tells the side.'], ...
        ['Both channels are lit, each for an amount. The side depends on A''s share of the '...
         'light (its relative abundance) or on A minus B, against a boundary you set; the total '...
         'light roves, so A has to be weighed against B. Controls: A alone or B alone decides, '...
         'the other channel a distractor.'], ...
        ['The window is cut into slots, each holding one flash of A, one of B, or nothing. A '...
         'group is a count of A and B flashes; more A pays left. The order of the flashes is '...
         'drawn anew every trial, so only the counts tell the side. Leave slots empty to make '...
         'both counts matter.'], ...
        ['A and B take turns, meeting in a short overlap: A first pays left, B first right. '...
         'The guarded cycle adds a long overlap and a random phase, so each channel on its '...
         'own looks the same on both sides and only their timing relative to each other '...
         'tells.'], ...
        ['Each group is a word: letters A, B, X (both) or - (dark), one flash per letter. '...
         'Words are listed for each side. With no simple rule separating the lists, the '...
         'animal has to learn each word as a whole.'], ...
        'Pulses typed in by hand, one row per pulse: group, channel, start and end (s).'}, ...
    'PerTrial', {'', 'new amounts every trial', 'a new order of the flashes every trial', ...
                 'a random phase every trial (guarded cycle)', '', ''});
